import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "@/payload-api"; // generated by openapi-typescript

export const fetchClient = createFetchClient<paths>({
  baseUrl: "http://localhost:3000",
});
export const API = createClient(fetchClient);

export default API;
